# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '15.0'

      - name: Build
        run: |
          xcodebuild build \
            -scheme "SwiftyFilters" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_REQUIRED=NO

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme "SwiftyFilters" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_REQUIRED=NO
